!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72f6b210>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!Exception: Expecting value: line 1 column 1 (char 0)!!Exception: Expecting value: line 1 column 1 (char 0)!!Exception: Expecting value: line 1 column 1 (char 0)!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72f5aeb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/forecast?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x737890d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/forecast?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73789610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/forecast?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x737fe090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/forecast?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x737fe5d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/forecast?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x737b0ff0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/forecast?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x737d5550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7377b0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/forecast?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73748f90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/forecast?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7376e4d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3fc70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f9b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f8d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f750>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f950>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f930>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f5d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3fa30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f8d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f9b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3fc70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f750>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f9f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3fa30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f8d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f9b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f8d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f7f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f8f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f750>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3fa10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3fc90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f8d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f7f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f8f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f750>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3fa10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3fc90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f8d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f7f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f8f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b3f750>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72d945b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72f95210>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))!!!Exception: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=463829&APPID=f46b1b286bb5568020e409cd1d1678b8&units=metric&lang=ru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72f732d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))